# Generated by Django 5.2.4 on 2025-07-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_terms_accepted'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_town_d46a74_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='town',
        ),
    ]
