# Generated by Django 5.2.4 on 2025-07-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rental_type', models.CharField(choices=[('room', 'Room'), ('apartment', 'Apartment'), ('cottage', 'Cottage')], default='room', max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=58)),
                ('day_price_cents', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_objects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['town'], name='listings_re_town_4ee065_idx'), models.Index(fields=['rental_type'], name='listings_re_rental__359bd0_idx')],
            },
        ),
    ]
