# Generated by Django 5.2.4 on 2025-07-12 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RentObjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rent_objects/')),
                ('uploaded_at', models.DateField(auto_now_add=True)),
                ('rent_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iamges', to='listings.rentobject')),
            ],
        ),
    ]
