# Generated by Django 5.2.4 on 2025-07-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rentobject_description_rentobjectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobjectimage',
            name='rent_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.rentobject'),
        ),
    ]
