# Generated by Django 5.2.4 on 2025-08-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_rentobjectimage_rent_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='reservation_edit_deadline',
            field=models.IntegerField(default=7),
        ),
    ]
