# Generated by Django 5.2.4 on 2025-08-22 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rentobject_reservation_edit_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='check_in_out_start_hour',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='own_bathroom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='own_kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='parking_place',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='rcheck_in_out_end_hour',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='reservation_break_minutes',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
    ]
