# Generated by Django 5.2.4 on 2025-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rentobject_area_rentobject_check_in_out_start_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentobject',
            name='area',
            field=models.FloatField(default=0),
        ),
    ]
