# Generated by Django 5.2.4 on 2025-08-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_rentobject_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentobject',
            old_name='rcheck_in_out_end_hour',
            new_name='check_in_out_end_hour',
        ),
    ]
