# Generated by Django 5.2.4 on 2025-08-27 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_rcheck_in_out_end_hour_rentobject_check_in_out_end_hour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rentobjectimage',
            options={'ordering': ['index']},
        ),
        migrations.RemoveField(
            model_name='rentobjectimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='rentobjectimage',
            name='index',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)]),
        ),
    ]
