# Generated by Django 5.2.4 on 2025-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_rentobjectimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentobject',
            name='reservation_break_minutes',
        ),
        migrations.AddField(
            model_name='rentobject',
            name='reservation_break_days',
            field=models.IntegerField(default=0),
        ),
    ]
