# Generated by Django 5.2.4 on 2025-08-30 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_rentobject_reservation_break_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentobject',
            old_name='check_in_out_end_hour',
            new_name='check_in_end_hour',
        ),
        migrations.RenameField(
            model_name='rentobject',
            old_name='check_in_out_start_hour',
            new_name='check_in_start_hour',
        ),
        migrations.AddField(
            model_name='rentobject',
            name='check_out_end_hour',
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name='rentobject',
            name='check_out_start_hour',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
