# Generated by Django 5.2.4 on 2025-08-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_check_in_out_end_hour_rentobject_check_in_end_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='advance_days',
            field=models.IntegerField(default=7),
        ),
    ]
