# Generated by Django 5.2.4 on 2025-09-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_rentobject_advance_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentobject',
            name='max_advance_days',
            field=models.IntegerField(default=365),
        ),
    ]
