# Generated by Django 5.2.4 on 2025-07-11 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='listings.rentobject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date_time'],
                'indexes': [models.Index(fields=['object', 'start_date_time'], name='reservation_object__de070d_idx')],
            },
        ),
    ]
