# Generated by Django 5.2.4 on 2025-08-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_date_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date_time',
            field=models.DateField(),
        ),
    ]
