# Generated by Django 5.2.4 on 2025-08-29 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_remove_rentobject_reservation_break_minutes_and_more'),
        ('reservations', '0003_alter_reservation_end_date_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_object__de070d_idx',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_date_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_date_time',
            new_name='start_date',
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['object', 'start_date'], name='reservation_object__2807f6_idx'),
        ),
    ]
