# Generated by Django 5.2.4 on 2025-09-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day_price_cents',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
