# Generated by Django 5.2.4 on 2025-09-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_day_price_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-01 12:00:00'),
            preserve_default=False,
        ),
    ]
